### ISSUE TITLE
FFMPEG IS MISSING!

### ISSUE THREAD

**Issue by 10362227** [developeranaz/Jdownloader-2-Rclone-Heroku#3]
When I download yt, It says FFMPEG IS MISSING!
![QQ截图20220202020948](https://user-images.githubusercontent.com/10655420/152025997-197ea2ee-d99b-430a-9af4-16ed02f21a46.jpg)

**Comment by developeranaz** [comment]
OK thanks for informing, i'll add it soon.

**Comment by developeranaz** [comment]
FFMPEG IS MISSING!
Fixed : https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku/commit/ec6b5684239109b2420ee1affbfdad6d0e39d762
Try redeploying [latest branch](https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku/tree/main)
